apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculo-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: veiculo-service
  template:
    metadata:
      labels:
        app: veiculo-service
    spec:
      containers:
        - name: questao02
          image: veiculo-microsservico:latest
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: veiculo-service
spec:
  selector:
    app: veiculo-microsservico
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
